language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
before_script:
- npm test
script: npm run build
before_deploy: npm install now --no-save
deploy:
  - provider: script
    script: now --token $NOW_TOKEN --public && now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true
