export default {
  guests: [
    {
      id: 'FR5c2qu6T_5eaj-wAABG',
      name: 'Anonymous-FR5c2qu6T_5eaj-wAABG',
      connection: {},
      dataChannel: {}
    }
  ],
  party: {
    name: 'octo',
    code: '1234',
    accessToken: 'BQB-eEYEOMp1_XshEt89U1xiY7IPpkifzd4csBfz37EX9HD2H6ciA81eRzTbnDDT8nTNX9HSDJpuN9dv218VHxn9_e4liQXuOWGmnpZN9kHiFWVfyiZshcrfu4qoLmWsVWCXlZtPLIgnpqDVipgh8J8TWVwDMx0',
    isStarted: false
  },
  player: null,
  tracks: {
    previous: [],
    next: [
      {
        album: {
          album_type: 'album',
          artists: [
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/1caBfBEapzw8z2Qz9q0OaQ'
              },
              href: 'https://api.spotify.com/v1/artists/1caBfBEapzw8z2Qz9q0OaQ',
              id: '1caBfBEapzw8z2Qz9q0OaQ',
              name: 'Asking Alexandria',
              type: 'artist',
              uri: 'spotify:artist:1caBfBEapzw8z2Qz9q0OaQ'
            }
          ],
          available_markets: [
            'AD',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'EC',
            'EE',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IS',
            'IT',
            'JP',
            'LI',
            'LT',
            'LU',
            'LV',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'PA',
            'PE',
            'PH',
            'PL',
            'PT',
            'PY',
            'RO',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/0dYHTESEegNj0dkIFGWy2d'
          },
          href: 'https://api.spotify.com/v1/albums/0dYHTESEegNj0dkIFGWy2d',
          id: '0dYHTESEegNj0dkIFGWy2d',
          images: [
            {
              height: 640,
              url: 'https://i.scdn.co/image/7ba2898aa98ef47ea70ade86a47ba014ec81811c',
              width: 640
            },
            {
              height: 300,
              url: 'https://i.scdn.co/image/c6309068dbb1f0fb21ea6539edca2d24a0d0104b',
              width: 300
            },
            {
              height: 64,
              url: 'https://i.scdn.co/image/a8ca4ac65af042fd484069564412174a9e39a05f',
              width: 64
            }
          ],
          name: 'Asking Alexandria',
          release_date: '2017-12-15',
          release_date_precision: 'day',
          type: 'album',
          uri: 'spotify:album:0dYHTESEegNj0dkIFGWy2d'
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/1caBfBEapzw8z2Qz9q0OaQ'
            },
            href: 'https://api.spotify.com/v1/artists/1caBfBEapzw8z2Qz9q0OaQ',
            id: '1caBfBEapzw8z2Qz9q0OaQ',
            name: 'Asking Alexandria',
            type: 'artist',
            uri: 'spotify:artist:1caBfBEapzw8z2Qz9q0OaQ'
          }
        ],
        available_markets: [
          'AD',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'EC',
          'EE',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IS',
          'IT',
          'JP',
          'LI',
          'LT',
          'LU',
          'LV',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'PA',
          'PE',
          'PH',
          'PL',
          'PT',
          'PY',
          'RO',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA'
        ],
        disc_number: 1,
        duration_ms: 237003,
        explicit: true,
        external_ids: {
          isrc: 'USYFZ1789101'
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/7zWPlO8Mcjc5mQGf7v8dlE'
        },
        href: 'https://api.spotify.com/v1/tracks/7zWPlO8Mcjc5mQGf7v8dlE',
        id: '7zWPlO8Mcjc5mQGf7v8dlE',
        is_local: false,
        name: 'Into The Fire',
        popularity: 64,
        preview_url: 'https://p.scdn.co/mp3-preview/c21355703ab360744f4ac13db67210aacaa36995?cid=4575b816fd8442629a54d119330a11c8',
        track_number: 2,
        type: 'track',
        uri: 'spotify:track:7zWPlO8Mcjc5mQGf7v8dlE',
        votes: []
      },
      {
        album: {
          album_type: 'album',
          artists: [
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/711MCceyCBcFnzjGY4Q7Un'
              },
              href: 'https://api.spotify.com/v1/artists/711MCceyCBcFnzjGY4Q7Un',
              id: '711MCceyCBcFnzjGY4Q7Un',
              name: 'AC/DC',
              type: 'artist',
              uri: 'spotify:artist:711MCceyCBcFnzjGY4Q7Un'
            }
          ],
          available_markets: [
            'AD',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'EC',
            'EE',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IS',
            'IT',
            'JP',
            'LI',
            'LT',
            'LU',
            'LV',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'PA',
            'PE',
            'PH',
            'PL',
            'PT',
            'PY',
            'RO',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/6mUdeDZCsExyJLMdAfDuwh'
          },
          href: 'https://api.spotify.com/v1/albums/6mUdeDZCsExyJLMdAfDuwh',
          id: '6mUdeDZCsExyJLMdAfDuwh',
          images: [
            {
              height: 640,
              url: 'https://i.scdn.co/image/52d83377fe9d7fc838deeb859499f3973adf903f',
              width: 640
            },
            {
              height: 300,
              url: 'https://i.scdn.co/image/b7b31914e0c4951249fad37271248212c8ac3025',
              width: 300
            },
            {
              height: 64,
              url: 'https://i.scdn.co/image/184dd6719f7c5317a08505d4d67795583adfb392',
              width: 64
            }
          ],
          name: 'Back In Black',
          release_date: '1980-07-25',
          release_date_precision: 'day',
          type: 'album',
          uri: 'spotify:album:6mUdeDZCsExyJLMdAfDuwh'
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/711MCceyCBcFnzjGY4Q7Un'
            },
            href: 'https://api.spotify.com/v1/artists/711MCceyCBcFnzjGY4Q7Un',
            id: '711MCceyCBcFnzjGY4Q7Un',
            name: 'AC/DC',
            type: 'artist',
            uri: 'spotify:artist:711MCceyCBcFnzjGY4Q7Un'
          }
        ],
        available_markets: [
          'AD',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'EC',
          'EE',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IS',
          'IT',
          'JP',
          'LI',
          'LT',
          'LU',
          'LV',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'PA',
          'PE',
          'PH',
          'PL',
          'PT',
          'PY',
          'RO',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA'
        ],
        disc_number: 1,
        duration_ms: 255493,
        explicit: false,
        external_ids: {
          isrc: 'AUAP08000046'
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/08mG3Y1vljYA6bvDt4Wqkj'
        },
        href: 'https://api.spotify.com/v1/tracks/08mG3Y1vljYA6bvDt4Wqkj',
        id: '08mG3Y1vljYA6bvDt4Wqkj',
        is_local: false,
        name: 'Back In Black',
        popularity: 82,
        preview_url: 'https://p.scdn.co/mp3-preview/506bc9a0485990973449b0467791e06174371284?cid=4575b816fd8442629a54d119330a11c8',
        track_number: 6,
        type: 'track',
        uri: 'spotify:track:08mG3Y1vljYA6bvDt4Wqkj',
        votes: []
      }
    ],
    queue: []
  }
}
